parameters:
  vmImage: 'ubuntu-latest'
  acrName: ''
  imageName: ''
  resourceGroup: ''
  containerName: ''
  buildId: $(Build.BuildId)

steps:
  - task: AzureCLI@2
    displayName: Deploy Docker Image to ACI
    inputs:
      connectedServiceNameARM: 'fulfill3d-subscription-alpha'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az container create \
          --resource-group $(resourceGroup) \
          --name $(containerName) \
          --image $(acrName).azurecr.io/$(imageName):latest \
          --cpu 1 \
          --memory 1 \
          --registry-login-server $(acrName).azurecr.io \
          --registry-username $(ACR_USERNAME) \
          --registry-password $(ACR_PASSWORD) \
          --ports 80
